### PR TITLE
New version 3.0.2

### PR DESCRIPTION
**Pull request by Oksydan**

### CODE REVIEW

**Comment by aponahamed** [comment]
Screenshot_4
why showing this error

**Comment by Oksydan** [comment]
Hi @aponahamed, 
Please create an issue in falcon repository.

**Comment by aponahamed** [comment]
How can i solved

**Comment by Oksydan** [comment]
Please, create an issue. We can discuss there. I need more information.

**Comment by aponahamed** [comment]
i already create issue please check

**Pull request merged**
